import { Activity, Building2, TrendingUp } from "lucide-react";
import { getBumexEntity } from "@/lib/entities/config";
import { cn } from "@/lib/utils";
import type { StaffingAssignment, StaffingPerson } from "@/types/staffing";
import type { BumexEntityCode } from "@/types/entity";

const DAY = 86_400_000;
function mondayOf(date: Date) { const copy = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate())); const day = copy.getUTCDay() || 7; copy.setUTCDate(copy.getUTCDate() - day + 1); return copy; }
function tone(value: number) { return value > 100 ? "bg-rose-500" : value >= 85 ? "bg-amber-500" : value >= 55 ? "bg-blue-500" : "bg-emerald-500"; }

export function StaffingInsights({ people, assignments, locale }: { people: StaffingPerson[]; assignments: StaffingAssignment[]; locale: "fr" | "en" }) {
  const fr = locale === "fr";
  const start = mondayOf(new Date());
  const totalCapacity = people.reduce((sum, person) => sum + Number(person.weekly_capacity_hours), 0);
  const weeks = Array.from({ length: 8 }, (_, index) => { const weekStart = new Date(start.getTime() + index * 7 * DAY); const weekEnd = new Date(weekStart.getTime() + 6 * DAY); const startIso = weekStart.toISOString().slice(0, 10); const endIso = weekEnd.toISOString().slice(0, 10); const allocated = assignments.filter(item => item.status === "confirmed" && item.start_date <= endIso && item.end_date >= startIso).reduce((sum, item) => sum + Number(item.weekly_hours), 0); return { start: weekStart, allocated, rate: totalCapacity ? Math.round((allocated / totalCapacity) * 100) : 0 }; });
  const today = new Date().toISOString().slice(0, 10);
  const entityCodes = [...new Set(people.map(person => person.entity_code).filter((code): code is BumexEntityCode => Boolean(code)))];
  const entities = entityCodes.map(code => { const members = people.filter(person => person.entity_code === code); const capacity = members.reduce((sum, person) => sum + Number(person.weekly_capacity_hours), 0); const ids = new Set(members.map(person => person.id)); const allocated = assignments.filter(item => ids.has(item.user_id) && item.status === "confirmed" && item.start_date <= today && item.end_date >= today).reduce((sum, item) => sum + Number(item.weekly_hours), 0); return { code, members: members.length, capacity, allocated, rate: capacity ? Math.round((allocated / capacity) * 100) : 0 }; }).sort((a,b) => b.rate-a.rate);
  const average = weeks.length ? Math.round(weeks.reduce((sum, week) => sum + week.rate, 0) / weeks.length) : 0;
  const peak = Math.max(0, ...weeks.map(week => week.rate));
  return <section className="grid gap-4 xl:grid-cols-[1.45fr_.85fr]">
    <article className="overflow-hidden rounded-[28px] border border-blue-200 bg-gradient-to-br from-blue-50 via-white to-cyan-50 shadow-[0_28px_80px_-58px_rgba(37,99,235,.65)] dark:border-blue-400/20 dark:from-blue-950/20 dark:via-background dark:to-cyan-950/20"><header className="flex items-start justify-between gap-4 border-b border-blue-100 px-5 py-4 dark:border-blue-400/15"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-700 dark:text-blue-300">{fr ? "Prévision" : "Forecast"}</p><h2 className="mt-1 font-semibold">{fr ? "Utilisation sur les 8 prochaines semaines" : "Utilization over the next 8 weeks"}</h2></div><TrendingUp className="size-5 text-blue-600" /></header><div className="p-5"><div className="flex h-52 items-end gap-2 sm:gap-3">{weeks.map(week => <div key={week.start.toISOString()} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><div className="relative flex h-40 w-full items-end overflow-hidden rounded-xl bg-slate-200/70 dark:bg-white/[.06]" title={`${week.rate}% · ${Number(week.allocated.toFixed(1))}h`}><div className={cn("w-full rounded-xl transition-all group-hover:brightness-110", tone(week.rate))} style={{ height: `${Math.min(100, Math.max(4, week.rate))}%` }} /><span className="absolute inset-x-0 top-2 text-center text-[10px] font-bold">{week.rate}%</span></div><span className="text-[10px] font-semibold text-muted-foreground">{new Intl.DateTimeFormat(fr ? "fr-FR" : "en-GB", { day: "numeric", month: "short", timeZone: "UTC" }).format(week.start)}</span></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-3">{[[fr ? "Moyenne" : "Average",`${average}%`],[fr ? "Pic de charge" : "Peak load",`${peak}%`],[fr ? "Capacité totale" : "Total capacity",`${totalCapacity}h`]].map(([label,value]) => <div key={label} className="rounded-xl border border-border/70 bg-card/75 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>)}</div></div></article>
    <article className="overflow-hidden rounded-[28px] border border-violet-200 bg-gradient-to-br from-violet-50 via-white to-fuchsia-50 shadow-[0_28px_80px_-58px_rgba(124,58,237,.55)] dark:border-violet-400/20 dark:from-violet-950/20 dark:via-background dark:to-fuchsia-950/20"><header className="flex items-start justify-between gap-4 border-b border-violet-100 px-5 py-4 dark:border-violet-400/15"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-700 dark:text-violet-300">{fr ? "Entités" : "Entities"}</p><h2 className="mt-1 font-semibold">{fr ? "Charge actuelle" : "Current load"}</h2></div><Building2 className="size-5 text-violet-600" /></header><div className="space-y-4 p-5">{entities.length ? entities.map(item => <div key={item.code}><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold">{getBumexEntity(item.code)?.name ?? item.code}</p><p className="text-[10px] text-muted-foreground">{item.members} {fr ? "collaborateur(s)" : "people"} · {Number(item.allocated.toFixed(1))}/{item.capacity}h</p></div><strong className={item.rate > 100 ? "text-sm text-rose-700 dark:text-rose-300" : "text-sm"}>{item.rate}%</strong></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-slate-200/75 dark:bg-white/[.07]"><div className={cn("h-full rounded-full", tone(item.rate))} style={{ width: `${Math.min(100,item.rate)}%` }} /></div></div>) : <p className="text-sm text-muted-foreground">{fr ? "Aucune donnée d’entité disponible." : "No entity data available."}</p>}<div className="flex items-center gap-2 rounded-xl border border-violet-200/70 bg-violet-500/[.06] p-3 text-xs text-muted-foreground"><Activity className="size-4 shrink-0 text-violet-600" />{fr ? "Calcul fondé sur les affectations confirmées." : "Based on confirmed assignments."}</div></div></article>
  </section>;
}
